-ifndef(LOADTEST_HRL).

-define(WRITER_LOG, "/tmp/loadtest_writer.log").
-define(READER_LOG, "/tmp/loadtest_reader.log").


-define(FSDATA, [{<<"Event-Name">>,<<"REQUEST_PARAMS">>},
                 {<<"Core-UUID">>,<<"54f49bf1-fa33-4b6f-8721-2fa5da559064">>},
                 {<<"FreeSWITCH-Hostname">>,<<"vagrant.2600hz.com">>},
                 {<<"FreeSWITCH-Switchname">>,<<"vagrant.2600hz.com">>},
                 {<<"FreeSWITCH-IPv4">>,<<"192.168.1.45">>},
                 {<<"FreeSWITCH-IPv6">>,<<"::1">>},
                 {<<"Event-Date-Local">>,<<"2012-05-01 12:46:15">>},
                 {<<"Event-Date-GMT">>,<<"Tue, 01 May 2012 19:46:15 GMT">>},
                 {<<"Event-Date-Timestamp">>,<<"1335901575907873">>},
                 {<<"Event-Calling-File">>,<<"mod_dialplan_xml.c">>},
                 {<<"Event-Calling-Function">>,<<"dialplan_xml_locate">>},
                 {<<"Event-Calling-Line-Number">>,<<"452">>},
                 {<<"Channel-State">>,<<"CS_ROUTING">>},
                 {<<"Channel-Call-State">>,<<"RINGING">>},
                 {<<"Channel-State-Number">>,<<"2">>},
                 {<<"Channel-Name">>,<<"sofia/sipinterface_1/device_1@kanderson.sip.2600hz.com">>},
                 {<<"Unique-ID">>,<<"1534596946@192.168.1.188">>},
                 {<<"Call-Direction">>,<<"inbound">>},
                 {<<"Presence-Call-Direction">>,<<"inbound">>},
                 {<<"Channel-HIT-Dialplan">>,<<"true">>},
                 {<<"Channel-Presence-ID">>,<<"device_1@kanderson.sip.2600hz.com">>},
                 {<<"Channel-Call-UUID">>,<<"1534596946@192.168.1.188">>},
                 {<<"Answer-State">>,<<"ringing">>},
                 {<<"Caller-Direction">>,<<"inbound">>},
                 {<<"Caller-Username">>,<<"device_1">>},
                 {<<"Caller-Dialplan">>,<<"XML">>},
                 {<<"Caller-Caller-ID-Name">>,<<"device_1">>},
                 {<<"Caller-Caller-ID-Number">>,<<"device_1">>},
                 {<<"Caller-Network-Addr">>,<<"192.168.1.188">>},
                 {<<"Caller-ANI">>,<<"device_1">>},
                 {<<"Caller-Destination-Number">>,<<"*97">>},
                 {<<"Caller-Unique-ID">>,<<"1534596946@192.168.1.188">>},
                 {<<"Caller-Source">>,<<"mod_sofia">>},
                 {<<"Caller-Context">>,<<"context_2">>},
                 {<<"Caller-Channel-Name">>,<<"sofia/sipinterface_1/device_1@kanderson.sip.2600hz.com">>},
                 {<<"Caller-Profile-Index">>,<<"1">>},
                 {<<"Caller-Profile-Created-Time">>,<<"1335901575907873">>},
                 {<<"Caller-Channel-Created-Time">>,<<"1335901575907873">>},
                 {<<"Caller-Channel-Answered-Time">>,<<"0">>},
                 {<<"Caller-Channel-Progress-Time">>,<<"0">>},
                 {<<"Caller-Channel-Progress-Media-Time">>,<<"0">>},
                 {<<"Caller-Channel-Hangup-Time">>,<<"0">>},
                 {<<"Caller-Channel-Transfer-Time">>,<<"0">>},
                 {<<"Caller-Screen-Bit">>,<<"true">>},
                 {<<"Caller-Privacy-Hide-Name">>,<<"false">>},
                 {<<"Caller-Privacy-Hide-Number">>,<<"false">>},
                 {<<"variable_direction">>,<<"inbound">>},
                 {<<"variable_uuid">>,<<"1534596946@192.168.1.188">>},
                 {<<"variable_session_id">>,<<"42">>},
                 {<<"variable_sip_local_network_addr">>,<<"192.168.1.45">>},
                 {<<"variable_sip_network_ip">>,<<"192.168.1.188">>},
                 {<<"variable_sip_network_port">>,<<"48426">>},
                 {<<"variable_sip_received_ip">>,<<"192.168.1.188">>},
                 {<<"variable_sip_received_port">>,<<"48426">>},
                 {<<"variable_sip_via_protocol">>,<<"udp">>},
                 {<<"variable_sip_authorized">>,<<"true">>},
                 {<<"variable_sip_number_alias">>,<<"device_1">>},
                 {<<"variable_sip_auth_username">>,<<"device_1">>},
                 {<<"variable_sip_auth_realm">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_number_alias">>,<<"device_1">>},
                 {<<"variable_user_name">>,<<"device_1">>},
                 {<<"variable_domain_name">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_ecallmgr_Authorizing-ID">>,<<"e00816343ee126968a5f18a0aa2442e4">>},
                 {<<"variable_ecallmgr_Inception">>,<<"on-net">>},
                 {<<"variable_ecallmgr_Authorizing-Type">>,<<"device">>},
                 {<<"variable_ecallmgr_Account-ID">>,<<"c0705d7474ea0160c10a351b2544006b">>},
                 {<<"variable_ecallmgr_Realm">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_ecallmgr_Username">>,<<"device_1">>},
                 {<<"variable_sip_from_user">>,<<"device_1">>},
                 {<<"variable_sip_from_uri">>,<<"device_1@kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_from_host">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_from_user_stripped">>,<<"device_1">>},
                 {<<"variable_sip_from_tag">>,<<"1876383538">>},
                 {<<"variable_sofia_profile_name">>,<<"sipinterface_1">>},
                 {<<"variable_sip_from_display">>,<<"device_1">>},
                 {<<"variable_sip_full_from">>,<<"\"device_1\" <sip:device_1@kanderson.sip.2600hz.com>;tag=1876383538">>},
                 {<<"variable_sip_full_to">>,<<"<sip:*97@kanderson.sip.2600hz.com>">>},
                 {<<"variable_sip_req_user">>,<<"*97">>},
                 {<<"variable_sip_req_uri">>,<<"*97@kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_req_host">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_to_user">>,<<"*97">>},
                 {<<"variable_sip_to_uri">>,<<"*97@kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_to_host">>,<<"kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_contact_user">>,<<"device_1">>},
                 {<<"variable_sip_contact_port">>,<<"48426">>},
                 {<<"variable_sip_contact_uri">>,<<"device_1@192.168.1.188:48426">>},
                 {<<"variable_sip_contact_host">>,<<"192.168.1.188">>},
                 {<<"variable_channel_name">>,<<"sofia/sipinterface_1/device_1@kanderson.sip.2600hz.com">>},
                 {<<"variable_sip_call_id">>,<<"1534596946@192.168.1.188">>},
                 {<<"variable_sip_user_agent">>,<<"Yealink SIP-T28P 2.60.0.110">>},
                 {<<"variable_sip_via_host">>,<<"192.168.1.188">>},
                 {<<"variable_sip_via_port">>,<<"48426">>},
                 {<<"variable_max_forwards">>,<<"70">>},
                 {<<"variable_presence_id">>,<<"device_1@kanderson.sip.2600hz.com">>},
                 {<<"variable_switch_r_sdp">>,<<"v=0\r\no=- 20003 20003 IN IP4 192.168.1.188\r\ns=SDP data\r\nc=IN IP4 192.168.1.188\r\nt=0 0\r\nm=audio 11786 RTP/AVP 0 8 18 9 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:18 G729/8000\r\na=fmtp:18 annexb=no\r\na=rtpmap:9 G722/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=ptime:20\r\n">>},
                 {<<"variable_ep_codec_string">>,<<"PCMU@8000h@20i@64000b,PCMA@8000h@20i@64000b">>},
                 {<<"variable_endpoint_disposition">>,<<"DELAYED NEGOTIATION">>},
                 {<<"variable_call_uuid">>,<<"1534596946@192.168.1.188">>},
                 {<<"Hunt-Direction">>,<<"inbound">>},
                 {<<"Hunt-Username">>,<<"device_1">>},
                 {<<"Hunt-Dialplan">>,<<"XML">>},
                 {<<"Hunt-Caller-ID-Name">>,<<"device_1">>},
                 {<<"Hunt-Caller-ID-Number">>,<<"device_1">>},
                 {<<"Hunt-Network-Addr">>,<<"192.168.1.188">>},
                 {<<"Hunt-ANI">>,<<"device_1">>},
                 {<<"Hunt-Destination-Number">>,<<"*97">>},
                 {<<"Hunt-Unique-ID">>,<<"1534596946@192.168.1.188">>},
                 {<<"Hunt-Source">>,<<"mod_sofia">>},
                 {<<"Hunt-Context">>,<<"context_2">>},
                 {<<"Hunt-Channel-Name">>,<<"sofia/sipinterface_1/device_1@kanderson.sip.2600hz.com">>},
                 {<<"Hunt-Profile-Index">>,<<"1">>},
                 {<<"Hunt-Profile-Created-Time">>,<<"1335901575907873">>},
                 {<<"Hunt-Channel-Created-Time">>,<<"1335901575907873">>},
                 {<<"Hunt-Channel-Answered-Time">>,<<"0">>},
                 {<<"Hunt-Channel-Progress-Time">>,<<"0">>},
                 {<<"Hunt-Channel-Progress-Media-Time">>,<<"0">>},
                 {<<"Hunt-Channel-Hangup-Time">>,<<"0">>},
                 {<<"Hunt-Channel-Transfer-Time">>,<<"0">>},
                 {<<"Hunt-Screen-Bit">>,<<"true">>},
                 {<<"Hunt-Privacy-Hide-Name">>,<<"false">>},
                 {<<"Hunt-Privacy-Hide-Number">>,<<"false">>}
                ]).
        
-define(LOADTEST_HRL, true).

-endif.
